export const LABELS = {
  MASTER: {
    TITLE: 'Master Data',
    AUTHOR: 'Penulis',
    PUBLISHER: 'Penerbit',
    CATEGORY: 'Kategori',
    NEW_AUTHOR: 'Tambah Penulis',
    NEW_PUBLISHER: 'Tambah Penerbit',
    NEW_CATEGORY: 'Tambah Kategori',
    EDIT_AUTHOR: 'Edit Penulis',
    EDIT_PUBLISHER: 'Edit Penerbit',
    EDIT_CATEGORY: 'Edit Kategori',
    SEARCH_AUTHOR: 'Cari penulis...',
    SEARCH_PUBLISHER: 'Cari penerbit...',
    SEARCH_CATEGORY: 'Cari kategori...',
    CODE: 'Kode',
    NAME: 'Nama',
    DESCRIPTION: 'Deskripsi',
    CONFIRM_DELETE_AUTHOR: 'Apakah Anda yakin ingin menghapus penulis ini?',
    CONFIRM_DELETE_PUBLISHER: 'Apakah Anda yakin ingin menghapus penerbit ini?',
    CONFIRM_DELETE_CATEGORY: 'Apakah Anda yakin ingin menghapus kategori ini?',
    SAVE: 'Simpan',
    CANCEL: 'Batal',
    DELETED: 'Berhasil dihapus.',
    CREATED: 'Berhasil ditambahkan.',
    UPDATED: 'Berhasil diperbarui.',
  },
  BOOK: {
    TITLE: 'Buku',
    SUBTITLE: 'Modul Buku sedang dalam pengembangan.',
    TABLE_HEADER: 'Daftar Buku',
    NEW: 'Tambah Buku',
    EDIT: 'Edit Buku',
    DETAIL: 'Detail Buku',
    DELETE: 'Hapus Buku',
    SEARCH_PLACEHOLDER: 'Cari judul atau ISBN...',
    REFRESH: 'Refresh',
    SAVE: 'Simpan',
    CANCEL: 'Batal',
    CONFIRM_DELETE: 'Apakah Anda yakin ingin menghapus buku ini?',
    DELETED: 'Buku berhasil dihapus.',
    CREATED: 'Buku berhasil ditambahkan.',
    UPDATED: 'Buku berhasil diperbarui.',
  },
  FIELD: {
    TITLE: 'Judul',
    ISBN: 'ISBN',
    CATEGORY: 'Kategori',
    PUBLISHER: 'Penerbit',
    YEAR: 'Tahun Terbit',
    EDITION: 'Edisi',
    LANGUAGE: 'Bahasa',
    PAGE_COUNT: 'Jumlah Halaman',
    DESCRIPTION: 'Deskripsi',
    AUTHORS: 'Penulis',
    COPY_COUNT: 'Jumlah Copy',
    ACTIONS: 'Aksi',
  },
  VALIDATION: {
    TITLE_REQUIRED: 'Judul wajib diisi.',
    ISBN_UNIQUE: 'ISBN sudah digunakan.',
    YEAR_NUMBER: 'Tahun harus berupa angka.',
  },
  PLACEHOLDER: {
    SELECT_CATEGORY: 'Pilih Kategori',
    SELECT_PUBLISHER: 'Pilih Penerbit',
    SELECT_AUTHORS: 'Pilih Penulis',
    NO_DATA: 'Tidak ada data.',
    LOADING: 'Memuat...',
  },
  ACTION: {
    VIEW: 'Lihat',
    EDIT: 'Edit',
    DELETE: 'Hapus',
  },
} as const
