export const LABELS = {
  MASTER: {
    TITLE: 'Master Data',
    AUTHOR: 'Penulis',
    PUBLISHER: 'Penerbit',
    CATEGORY: 'Kategori',
    NEW_AUTHOR: 'Tambah Penulis',
    NEW_PUBLISHER: 'Tambah Penerbit',
    NEW_CATEGORY: 'Tambah Kategori',
    EDIT_AUTHOR: 'Edit Penulis',
    EDIT_PUBLISHER: 'Edit Penerbit',
    EDIT_CATEGORY: 'Edit Kategori',
    SEARCH_AUTHOR: 'Cari penulis...',
    SEARCH_PUBLISHER: 'Cari penerbit...',
    SEARCH_CATEGORY: 'Cari kategori...',
    CODE: 'Kode',
    NAME: 'Nama',
    DESCRIPTION: 'Deskripsi',
    CONFIRM_DELETE_AUTHOR: 'Apakah Anda yakin ingin menghapus penulis ini?',
    CONFIRM_DELETE_PUBLISHER: 'Apakah Anda yakin ingin menghapus penerbit ini?',
    CONFIRM_DELETE_CATEGORY: 'Apakah Anda yakin ingin menghapus kategori ini?',
    SAVE: 'Simpan',
    CANCEL: 'Batal',
    DELETED: 'Berhasil dihapus.',
    CREATED: 'Berhasil ditambahkan.',
    UPDATED: 'Berhasil diperbarui.',
  },
  BOOK: {
    TITLE: 'Buku',
    SUBTITLE: 'Modul Buku sedang dalam pengembangan.',
    TABLE_HEADER: 'Daftar Buku',
    NEW: 'Tambah Buku',
    EDIT: 'Edit Buku',
    DETAIL: 'Detail Buku',
    DELETE: 'Hapus Buku',
    SEARCH_PLACEHOLDER: 'Cari judul atau ISBN...',
    REFRESH: 'Refresh',
    SAVE: 'Simpan Buku',
    CANCEL: 'Batal',
    SAVE_DRAFT: 'Simpan Draft',
    CONFIRM_DELETE: 'Apakah Anda yakin ingin menghapus buku ini?',
    DELETED: 'Buku berhasil dihapus.',
    CREATED: 'Buku berhasil ditambahkan.',
    UPDATED: 'Buku berhasil diperbarui.',
  },
  BOOK_SECTION: {
    MAIN_INFO: 'Informasi Utama',
    BIBLIOGRAPHY: 'Detail Bibliografi',
    PROCUREMENT: 'Informasi Pengadaan',
    COVER: 'Sampul Buku',
    SUMMARY: 'Ringkasan',
    COPIES: 'Eksemplar Buku',
  },
  MEMBER: {
    TITLE: 'Anggota',
    NEW: 'Tambah Anggota',
    EDIT: 'Edit Anggota',
    DETAIL: 'Detail Anggota',
    SAVE: 'Simpan Anggota',
    SAVE_CHANGES: 'Simpan Perubahan',
    SAVE_DRAFT: 'Simpan Draft',
    CANCEL: 'Batal',
    PRINT_CARD: 'Cetak Kartu',
    STATUS_MEMBERSHIP: 'Status Keanggotaan',
    STATISTICS: 'Statistik',
    CURRENTLY_BORROWED: 'Sedang Dipinjam',
    TOTAL_BORROWED: 'Total Dipinjam',
    LATE_RETURNS: 'Keterlambatan',
    NO_BORROWING_HISTORY: 'Belum ada riwayat peminjaman.',
    NO_BORROWING_HISTORY_DESC: 'Belum ada riwayat peminjaman untuk anggota ini.',
    NO_FINE_HISTORY: 'Belum ada riwayat denda.',
    NO_FINE_HISTORY_DESC: 'Anggota ini tidak memiliki catatan denda.',
    CREATED: 'Anggota berhasil ditambahkan.',
    UPDATED: 'Anggota berhasil diperbarui.',
  },
  MEMBER_TAB: {
    INFO: 'Informasi',
    BORROWING: 'Riwayat Peminjaman',
    FINE: 'Riwayat Denda',
    ACTIVITY: 'Aktivitas',
  },
  MEMBER_SECTION: {
    PERSONAL: 'Data Pribadi',
    MEMBERSHIP: 'Keanggotaan',
    ADDRESS: 'Alamat',
    NOTES: 'Catatan',
    PHOTO: 'Foto Anggota',
    SUMMARY: 'Ringkasan Anggota',
    RIGHTS: 'Hak Peminjaman',
  },
  FIELD: {
    TITLE: 'Judul',
    ISBN: 'ISBN',
    CATEGORY: 'Kategori',
    PUBLISHER: 'Penerbit',
    YEAR: 'Tahun Terbit',
    EDITION: 'Edisi',
    LANGUAGE: 'Bahasa',
    PAGE_COUNT: 'Jumlah Halaman',
    DESCRIPTION: 'Deskripsi',
    AUTHORS: 'Penulis',
    COPY_COUNT: 'Jumlah Copy',
    ACTIONS: 'Aksi',
    ACQUISITION_DATE: 'Tanggal Perolehan',
    ACQUISITION_SOURCE: 'Sumber Perolehan',
    PRICE: 'Harga Beli',
    NOTES: 'Catatan',
    INITIAL_COPIES: 'Jumlah Eksemplar Awal',
    FULL_NAME: 'Nama Lengkap',
    GENDER: 'Jenis Kelamin',
    MALE: 'Laki-laki',
    FEMALE: 'Perempuan',
    BIRTHPLACE: 'Tempat Lahir',
    BIRTH_DATE: 'Tanggal Lahir',
    PHONE: 'No HP',
    EMAIL: 'Email',
    MEMBER_NUMBER: 'Nomor Anggota',
    MEMBER_TYPE: 'Tipe Anggota',
    STUDENT: 'Siswa',
    TEACHER: 'Guru',
    GENERAL: 'Umum',
    JOIN_DATE: 'Tanggal Daftar',
    VALID_UNTIL: 'Berlaku Hingga',
    STATUS: 'Status',
    ACTIVE: 'Aktif',
    INACTIVE: 'Nonaktif',
    ADDRESS: 'Alamat Lengkap',
    DISTRICT: 'Kecamatan',
    VILLAGE: 'Kelurahan / Desa',
    CITY: 'Kota / Kabupaten',
    POSTAL_CODE: 'Kode Pos',
    MAX_BOOKS: 'Maks Buku',
    MAX_DAYS: 'Lama Pinjam',
    EXTENSIONS: 'Perpanjangan',
    UNLIMITED: 'Tidak Terbatas',
    DAYS: 'Hari',
    TIMES: 'x',
  },
  PLACEHOLDER: {
    SELECT_CATEGORY: 'Pilih Kategori',
    SELECT_PUBLISHER: 'Pilih Penerbit',
    SELECT_AUTHORS: 'Pilih Penulis',
    NO_DATA: 'Tidak ada data.',
    LOADING: 'Memuat...',
    LANGUAGE: 'Pilih bahasa',
    EDITION: 'Contoh: Edisi 1',
    PAGE_COUNT: 'Contoh: 250',
    DESCRIPTION: 'Masukkan deskripsi atau sinopsis buku...',
    ACQUISITION_SOURCE: 'Pembelian / Donasi / Hibah',
    MEMBER_NUMBER: 'AUTO GENERATE',
    MEMBER_NOTES: 'Masukkan catatan anggota...',
    ADDRESS: 'Masukkan alamat lengkap...',
    BIRTHPLACE: 'Contoh: Jakarta',
  },
  COVER: {
    UPLOAD: 'Upload Sampul Buku',
    FORMAT: 'PNG JPG JPEG',
    SIZE: 'Max 2 MB',
  },
  MEMBER_COVER: {
    UPLOAD: 'Upload Foto Anggota',
    FORMAT: 'PNG JPG JPEG',
    SIZE: 'Max 2 MB',
  },
  COPIES_INFO: 'Biarkan 0 jika ingin menambahkan eksemplar melalui menu Inventaris.',
  COPY: {
    TITLE: 'Eksemplar Buku',
    ADD: 'Tambah Eksemplar',
    ADD_TITLE: 'Tambah Eksemplar Baru',
    DECOMMISSION: 'Hapus dari Koleksi',
    QUANTITY: 'Jumlah',
    SHELF_LOCATION: 'Lokasi Rak',
    CONDITION: 'Kondisi',
    CONDITION_INITIAL: 'Kondisi Awal',
    INVENTORY_NUMBER: 'Nomor Inventaris',
    BARCODE: 'Barcode',
    STATUS: 'Status',
    BARCODE_AUTO: 'Barcode akan dibuat otomatis.',
    INV_AUTO: 'Nomor inventaris akan dibuat otomatis dengan format INV-000001',
    NO_COPIES: 'Belum ada eksemplar.',
    CONFIRM_DECOMMISSION: 'Apakah Anda yakin ingin menghapus eksemplar ini dari koleksi?',
    CONFIRM_DECOMMISSION_WITH_HISTORY: 'Eksemplar ini memiliki riwayat peminjaman dan akan diubah statusnya menjadi REMOVED. Lanjutkan?',
    ADDED: 'Eksemplar berhasil ditambahkan.',
    DECOMMISSIONED: 'Eksemplar berhasil dihapus dari koleksi.',
    CREATING: 'Menambahkan eksemplar...',
    CONDITION_MAP: {
      GOOD: 'Baik',
      LIGHT_DAMAGE: 'Rusak Ringan',
      HEAVY_DAMAGE: 'Rusak Berat',
    },
  },
  MEMBER_NUMBER_INFO: 'Nomor anggota dibuat otomatis.',
  OPTIONAL: 'Opsional',
  LANGUAGES: [
    { value: 'id', label: 'Bahasa Indonesia' },
    { value: 'en', label: 'English' },
    { value: 'ar', label: 'العربية' },
    { value: 'zh', label: '中文' },
    { value: 'ja', label: '日本語' },
    { value: 'ko', label: '한국어' },
    { value: 'fr', label: 'Français' },
    { value: 'de', label: 'Deutsch' },
    { value: 'nl', label: 'Nederlands' },
    { value: 'es', label: 'Español' },
    { value: 'pt', label: 'Português' },
    { value: 'ru', label: 'Русский' },
  ],
  GENDERS: [
    { value: 'male', label: 'Laki-laki' },
    { value: 'female', label: 'Perempuan' },
  ],
  MEMBER_TYPES: [
    { value: 'student', label: 'Siswa' },
    { value: 'teacher', label: 'Guru' },
    { value: 'general', label: 'Umum' },
  ],
  MEMBER_STATUSES: [
    { value: 'active', label: 'Aktif' },
    { value: 'inactive', label: 'Nonaktif' },
  ],
  MEMBER_RIGHTS: {
    student: { maxBooks: 2, maxDays: 7, extensions: '1x' },
    teacher: { maxBooks: 5, maxDays: 30, extensions: '3x' },
    general: { maxBooks: 10, maxDays: 90, extensions: 'Tidak Terbatas' },
  },
  ACTION: {
    VIEW: 'Lihat',
    EDIT: 'Edit',
    DELETE: 'Hapus',
  },
} as const
