import {
  MEMBER_TYPES as MEMBER_TYPE_DEFINITIONS,
  MEMBER_TYPE_CODES,
  type MemberBorrowRights,
  type MemberTypeCode
} from '../shared/config/member-type'

const MEMBER_TYPE_OPTIONS: { value: MemberTypeCode; label: string }[] = MEMBER_TYPE_CODES.map((code) => ({
  value: code,
  label: MEMBER_TYPE_DEFINITIONS[code].label
}))

const MEMBER_RIGHTS_LOOKUP = Object.fromEntries(
  MEMBER_TYPE_CODES.map((code) => [code, MEMBER_TYPE_DEFINITIONS[code].borrowRights])
) as Record<MemberTypeCode, MemberBorrowRights>

export const LABELS = {
  MASTER: {
    TITLE: 'Master Data',
    AUTHOR: 'Penulis',
    PUBLISHER: 'Penerbit',
    CATEGORY: 'Kategori',
    NEW_AUTHOR: 'Tambah Penulis',
    NEW_PUBLISHER: 'Tambah Penerbit',
    NEW_CATEGORY: 'Tambah Kategori',
    EDIT_AUTHOR: 'Edit Penulis',
    EDIT_PUBLISHER: 'Edit Penerbit',
    EDIT_CATEGORY: 'Edit Kategori',
    SEARCH_AUTHOR: 'Cari penulis...',
    SEARCH_PUBLISHER: 'Cari penerbit...',
    SEARCH_CATEGORY: 'Cari kategori...',
    CODE: 'Kode',
    NAME: 'Nama',
    DESCRIPTION: 'Deskripsi',
    CONFIRM_DELETE_AUTHOR: 'Apakah Anda yakin ingin menghapus penulis ini?',
    CONFIRM_DELETE_PUBLISHER: 'Apakah Anda yakin ingin menghapus penerbit ini?',
    CONFIRM_DELETE_CATEGORY: 'Apakah Anda yakin ingin menghapus kategori ini?',
    SAVE: 'Simpan',
    CANCEL: 'Batal',
    DELETED: 'Berhasil dihapus.',
    CREATED: 'Berhasil ditambahkan.',
    UPDATED: 'Berhasil diperbarui.',
  },
  DASHBOARD: {
    LOAD_ERROR: 'Gagal memuat data dashboard.',
    RETRY: 'Coba Lagi',
    ACTIVITY_EMPTY: 'Belum ada aktivitas.',
    IMPORT_TITLE: 'Import Data',
    IMPORT_BOOKS: 'Import Buku',
    IMPORT_BOOKS_DESC: 'Import data buku secara massal dari file yang didukung.',
    IMPORT_MEMBERS: 'Import Anggota',
    IMPORT_MEMBERS_DESC: 'Import data anggota secara massal menggunakan fitur import anggota yang sudah tersedia.',
    IMPORT_BOOKS_CTA: 'Buka',
    IMPORT_MEMBERS_CTA: 'Mulai',
  },
  ACADEMIC_YEAR: {
    TITLE: 'Tahun Ajaran',
    NEW: 'Tambah Tahun Ajaran',
    EDIT: 'Edit Tahun Ajaran',
    SEARCH: 'Cari tahun ajaran...',
    NAME: 'Nama Tahun',
    START_DATE: 'Tanggal Mulai',
    END_DATE: 'Tanggal Selesai',
    STATUS: 'Status',
    CONFIRM_DELETE: 'Apakah Anda yakin ingin menghapus tahun ajaran ini?',
    ACTIVATE: 'Buka Tahun',
    DEACTIVATE: 'Tutup Tahun',
    ACTIVATE_CONFIRM: 'Aktifkan tahun ini? Tahun ajaran aktif lain akan otomatis dinonaktifkan.',
    DEACTIVATE_CONFIRM: 'Tutup tahun ini? Satu-satunya tahun aktif tidak dapat ditutup.',
    ACTIVATED: 'Tahun ajaran berhasil dibuka.',
    DEACTIVATED: 'Tahun ajaran berhasil ditutup.',
    DELETED: 'Tahun ajaran berhasil dihapus.',
    CREATED: 'Tahun ajaran berhasil ditambahkan.',
    UPDATED: 'Tahun ajaran berhasil diperbarui.',
  },
  CURRICULUM: {
    TITLE: 'Kurikulum',
    NEW: 'Tambah Kurikulum',
    EDIT: 'Edit Kurikulum',
    SEARCH: 'Cari kurikulum...',
    NAME: 'Nama',
    CONFIRM_DELETE: 'Apakah Anda yakin ingin menghapus kurikulum ini?',
    DELETED: 'Kurikulum berhasil dihapus.',
    CREATED: 'Kurikulum berhasil ditambahkan.',
    UPDATED: 'Kurikulum berhasil diperbarui.',
  },
  CLASS: {
    TITLE: 'Kelas',
    NEW: 'Tambah Kelas',
    EDIT: 'Edit Kelas',
    SEARCH: 'Cari kelas...',
    YEAR: 'Tahun Ajaran',
    CURRICULUM: 'Kurikulum',
    LEVEL: 'Tingkat',
    PARALLEL: 'Paralel',
    HOMEROOM_TEACHER: 'Guru Kelas',
    ALL_YEARS: 'Semua Tahun Ajaran',
    ALL_CURRICULA: 'Semua Kurikulum',
    SELECT_YEAR: 'Pilih Tahun Ajaran',
    SELECT_CURRICULUM: 'Pilih Kurikulum',
    SELECT_LEVEL: 'Pilih Tingkat',
    CONFIRM_DELETE: 'Apakah Anda yakin ingin menghapus kelas ini?',
    IMMUTABLE_HINT: 'Tingkat dan paralel tidak dapat diubah. Buat kelas baru untuk rename.',
    DELETED: 'Kelas berhasil dihapus.',
    CREATED: 'Kelas berhasil ditambahkan.',
    UPDATED: 'Kelas berhasil diperbarui.',
    CLONE: 'Clone ke Tahun Baru',
    CLONE_TITLE: 'Clone Struktur Kelas',
    CLONE_SOURCE_YEAR: 'Tahun Sumber',
    CLONE_TARGET_YEAR: 'Tahun Target',
    CLONE_RUN: 'Clone Kelas',
    CLONE_CLOSING: 'Selesai',
    CLONE_RESULT_CREATED: 'kelas dibuat',
    CLONE_RESULT_SKIPPED: 'kelas dilewati (sudah ada)',
    CLONE_NOTE: 'Menyalin kurikulum, tingkat, dan paralel. Guru kelas diatur kosong dan status aktif.',
  },
  BOOK: {
    TITLE: 'Buku',
    SUBTITLE: 'Modul Buku sedang dalam pengembangan.',
    TABLE_HEADER: 'Daftar Buku',
    NEW: 'Tambah Buku',
    EDIT: 'Edit Buku',
    DETAIL: 'Detail Buku',
    DELETE: 'Hapus Buku',
    SEARCH_PLACEHOLDER: 'Cari judul atau ISBN...',
    REFRESH: 'Refresh',
    SAVE: 'Simpan Buku',
    CANCEL: 'Batal',
    SAVE_DRAFT: 'Simpan Draft',
    CONFIRM_DELETE: 'Apakah Anda yakin ingin menghapus buku ini?',
    DELETE_ERROR: 'Gagal menghapus buku.',
    DELETED: 'Buku berhasil dihapus.',
    CREATED: 'Buku berhasil ditambahkan.',
    UPDATED: 'Buku berhasil diperbarui.',
    IMPORT: 'Import Buku',
  },
  BOOK_SECTION: {
    MAIN_INFO: 'Informasi Utama',
    BIBLIOGRAPHY: 'Detail Bibliografi',
    PROCUREMENT: 'Informasi Pengadaan',
    COVER: 'Sampul Buku',
    SUMMARY: 'Ringkasan',
    COPIES: 'Eksemplar Buku',
  },
  MEMBER: {
    TITLE: 'Anggota',
    NEW: 'Tambah Anggota',
    EDIT: 'Edit Anggota',
    DETAIL: 'Detail Anggota',
    SAVE: 'Simpan Anggota',
    SAVE_CHANGES: 'Simpan Perubahan',
    SAVE_DRAFT: 'Simpan Draft',
    CANCEL: 'Batal',
    PRINT_CARD: 'Cetak Kartu',
    STATUS_MEMBERSHIP: 'Status Keanggotaan',
    ELIGIBLE: 'Berhak Meminjam',
    NOT_ELIGIBLE: 'Tidak Berhak Meminjam',
    STATISTICS: 'Statistik',
    CURRENTLY_BORROWED: 'Sedang Dipinjam',
    TOTAL_BORROWED: 'Total Dipinjam',
    LATE_RETURNS: 'Keterlambatan',
    NO_BORROWING_HISTORY: 'Belum ada riwayat peminjaman.',
    NO_BORROWING_HISTORY_DESC: 'Belum ada riwayat peminjaman untuk anggota ini.',
    NO_FINE_HISTORY: 'Belum ada riwayat denda.',
    NO_FINE_HISTORY_DESC: 'Anggota ini tidak memiliki catatan denda.',
    CREATED: 'Anggota berhasil ditambahkan.',
    UPDATED: 'Anggota berhasil diperbarui.',
  },
  MEMBER_TAB: {
    INFO: 'Informasi',
    BORROWING: 'Riwayat Peminjaman',
    FINE: 'Riwayat Denda',
    ACTIVITY: 'Aktivitas',
  },
  MEMBER_SECTION: {
    PERSONAL: 'Data Pribadi',
    MEMBERSHIP: 'Keanggotaan',
    ADDRESS: 'Alamat',
    NOTES: 'Catatan',
    PHOTO: 'Foto Anggota',
    SUMMARY: 'Ringkasan Anggota',
    RIGHTS: 'Hak Peminjaman',
  },
  MEMBER_CLASS: {
    TITLE: 'Penempatan Kelas',
    SUBTITLE: 'Pilih Tahun Ajaran dan Kelas untuk anggota siswa.',
    ACADEMIC_YEAR: 'Tahun Ajaran',
    SELECT_YEAR: 'Pilih Tahun Ajaran',
    CLASS: 'Kelas',
    SELECT_CLASS: 'Pilih Kelas',
    YEAR_EMPTY: 'Tidak ada tahun ajaran untuk dipilih. Buat tahun ajaran terlebih dulu.',
    CLASS_EMPTY: 'Tidak ada kelas pada tahun ajaran ini.',
    REQUIRED_STUDENT: 'Anggota siswa wajib memilih Tahun Ajaran dan Kelas.',
  },
  FIELD: {
    TITLE: 'Judul',
    ISBN: 'ISBN',
    CATEGORY: 'Kategori',
    PUBLISHER: 'Penerbit',
    YEAR: 'Tahun Terbit',
    EDITION: 'Edisi',
    LANGUAGE: 'Bahasa',
    PAGE_COUNT: 'Jumlah Halaman',
    DESCRIPTION: 'Deskripsi',
    AUTHORS: 'Penulis',
    COPY_COUNT: 'Jumlah Copy',
    ACTIONS: 'Aksi',
    ACQUISITION_DATE: 'Tanggal Perolehan',
    ACQUISITION_SOURCE: 'Sumber Perolehan',
    ACQUISITION_COST: 'Harga Perolehan',
    ACQUISITION_SOURCE_DETAIL: 'Jelaskan Sumber Perolehan',
    ACQUISITION_NOTES: 'Catatan Pengadaan',
    PRICE: 'Harga Beli',
    NOTES: 'Catatan',
    INITIAL_COPIES: 'Jumlah Eksemplar Awal',
    FULL_NAME: 'Nama Lengkap',
    GENDER: 'Jenis Kelamin',
    MALE: 'Laki-laki',
    FEMALE: 'Perempuan',
    BIRTHPLACE: 'Tempat Lahir',
    BIRTH_DATE: 'Tanggal Lahir',
    PHONE: 'No HP',
    EMAIL: 'Email',
    MEMBER_NUMBER: 'Nomor Anggota',
    MEMBER_TYPE: 'Tipe Anggota',
    STUDENT: 'Siswa',
    TEACHER: 'Guru',
    GENERAL: 'Umum',
    JOIN_DATE: 'Tanggal Daftar',
    VALID_UNTIL: 'Berlaku Hingga',
    STATUS: 'Status',
    MEMBERSHIP_STATUS: 'Status Keanggotaan',
    BORROW_ELIGIBILITY: 'Eligibilitas Peminjaman',
    ACTIVE: 'Aktif',
    INACTIVE: 'Nonaktif',
    ADDRESS: 'Alamat Lengkap',
    DISTRICT: 'Kecamatan',
    VILLAGE: 'Kelurahan / Desa',
    CITY: 'Kota / Kabupaten',
    POSTAL_CODE: 'Kode Pos',
    MAX_BOOKS: 'Maks Buku',
    MAX_DAYS: 'Lama Pinjam',
    EXTENSIONS: 'Perpanjangan',
    UNLIMITED: 'Tidak Terbatas',
    DAYS: 'Hari',
    TIMES: 'x',
  },
  PLACEHOLDER: {
    SELECT_CATEGORY: 'Pilih Kategori',
    SELECT_PUBLISHER: 'Pilih Penerbit',
    SELECT_AUTHORS: 'Pilih Penulis',
    NO_DATA: 'Tidak ada data.',
    LOADING: 'Memuat...',
    LANGUAGE: 'Pilih bahasa',
    EDITION: 'Contoh: Edisi 1',
    PAGE_COUNT: 'Contoh: 250',
    DESCRIPTION: 'Masukkan deskripsi atau sinopsis buku...',
    ACQUISITION_SOURCE: 'Pembelian / Donasi / Hibah',
    MEMBER_NUMBER: 'AUTO GENERATE',
    MEMBER_NOTES: 'Masukkan catatan anggota...',
    ADDRESS: 'Masukkan alamat lengkap...',
    BIRTHPLACE: 'Contoh: Jakarta',
  },
  COVER: {
    UPLOAD: 'Upload Sampul Buku',
    FORMAT: 'PNG JPG JPEG',
    SIZE: 'Max 2 MB',
    CHANGE: 'Ganti Sampul',
    REMOVE: 'Hapus Sampul',
    REMOVE_TITLE: 'Hapus Sampul Buku',
    REMOVE_CONFIRM: 'Apakah Anda yakin ingin menghapus sampul buku ini?',
    REMOVED: 'Sampul berhasil dihapus.',
    UPLOADING: 'Memuat sampul...',
    PICKING: 'Memilih file...',
    PICK_ERROR: 'Gagal memilih file sampul.',
  },
  MEMBER_COVER: {
    UPLOAD: 'Upload Foto Anggota',
    FORMAT: 'PNG JPG JPEG',
    SIZE: 'Max 2 MB',
    CHANGE: 'Ganti Foto',
    REMOVE: 'Hapus Foto',
    REMOVE_TITLE: 'Hapus Foto Anggota',
    REMOVE_CONFIRM: 'Apakah Anda yakin ingin menghapus foto anggota ini?',
    REMOVED: 'Foto berhasil dihapus.',
    UPLOADING: 'Memuat foto...',
    PICKING: 'Memilih file...',
    PICK_ERROR: 'Gagal memilih file foto.',
    REMOVE_ERROR: 'Gagal menghapus foto anggota.',
  },
  COPIES_INFO: 'Biarkan 0 jika ingin menambahkan eksemplar melalui menu Inventaris.',
  COPY: {
    TITLE: 'Eksemplar Buku',
    ADD: 'Tambah Eksemplar',
    PRINT_LABELS: 'Cetak Label',
    ADD_TITLE: 'Tambah Eksemplar Baru',
    DECOMMISSION: 'Hapus dari Koleksi',
    QUANTITY: 'Jumlah',
    SHELF_LOCATION: 'Lokasi Rak',
    CONDITION: 'Kondisi',
    CONDITION_INITIAL: 'Kondisi Awal',
    INVENTORY_NUMBER: 'Nomor Inventaris',
    BARCODE: 'Barcode',
    STATUS: 'Status',
    BARCODE_AUTO: 'Barcode akan dibuat otomatis.',
    INV_AUTO: 'Nomor inventaris akan dibuat otomatis dengan format INV-000001',
    NO_COPIES: 'Belum ada eksemplar.',
    CONFIRM_DECOMMISSION: 'Apakah Anda yakin ingin menghapus eksemplar ini dari koleksi?',
    CONFIRM_DECOMMISSION_WITH_HISTORY: 'Eksemplar ini memiliki riwayat peminjaman dan akan diubah statusnya menjadi REMOVED. Lanjutkan?',
    ADDED: 'Eksemplar berhasil ditambahkan.',
    DECOMMISSIONED: 'Eksemplar berhasil dihapus dari koleksi.',
    CREATING: 'Menambahkan eksemplar...',
    CONDITION_MAP: {
      GOOD: 'Baik',
      LIGHT_DAMAGE: 'Rusak Ringan',
      HEAVY_DAMAGE: 'Rusak Berat',
    },
  },
  MEMBER_NUMBER_INFO: 'Nomor anggota dibuat otomatis.',
  OPTIONAL: 'Opsional',
  LANGUAGES: [
    { value: 'id', label: 'Bahasa Indonesia' },
    { value: 'en', label: 'English' },
    { value: 'ar', label: 'العربية' },
    { value: 'zh', label: '中文' },
    { value: 'ja', label: '日本語' },
    { value: 'ko', label: '한국어' },
    { value: 'fr', label: 'Français' },
    { value: 'de', label: 'Deutsch' },
    { value: 'nl', label: 'Nederlands' },
    { value: 'es', label: 'Español' },
    { value: 'pt', label: 'Português' },
    { value: 'ru', label: 'Русский' },
  ],
  GENDERS: [
    { value: 'male', label: 'Laki-laki' },
    { value: 'female', label: 'Perempuan' },
  ],
  MEMBER_TYPES: MEMBER_TYPE_OPTIONS,
  MEMBER_STATUSES: [
    { value: 'active', label: 'Aktif' },
    { value: 'inactive', label: 'Nonaktif' },
  ],
  MEMBER_RIGHTS: MEMBER_RIGHTS_LOOKUP,
  ACQUISITION_SOURCES: [
    { value: 'PEMBELIAN', label: 'Pembelian' },
    { value: 'DONASI', label: 'Donasi' },
    { value: 'HIBAH', label: 'Hibah' },
    { value: 'BANTUAN_PEMERINTAH', label: 'Bantuan Pemerintah' },
    { value: 'LAINNYA', label: 'Lainnya' },
  ],
  ACQUISITION_SOURCE_DETAIL_PLACEHOLDER: 'Jelaskan sumber perolehan...',
  IMPORT: {
    TITLE: 'Import Buku',
    SUBTITLE: 'Impor data buku dari file Excel (.xlsx).',
    DROPZONE_TITLE: 'Seret & lepas file Excel di sini',
    DROPZONE_HINT: 'atau klik untuk memilih file',
    FORMAT: 'Format file: .xlsx',
    MAX_SIZE_PREFIX: 'Maksimal ukuran file:',
    NO_FILE: 'Belum ada file yang dipilih. File wajib dipilih sebelum melanjutkan.',
    PARSING: 'Memproses file Excel...',
    READY: 'File siap diproses.',
    REPLACE: 'Ganti File',
    REMOVE: 'Hapus File',
    DOWNLOAD_TEMPLATE: 'Download Template',
    DOWNLOAD_SUCCESS: 'Template Import Buku v2 berhasil diunduh.',
    DOWNLOAD_CANCELLED: 'Unduhan template dibatalkan.',
    DOWNLOAD_ERROR: 'Gagal mengunduh template.',
    CONTINUE: 'Lanjut',
    BACK: 'Kembali',
    ERROR_REQUIRED: 'File wajib dipilih.',
    ERROR_EXTENSION: 'Hanya file .xlsx yang didukung.',
    ERROR_SIZE: 'Ukuran file melebihi batas maksimal.',
    ERROR_READ_FAILED: 'File gagal dibaca. Pastikan file merupakan .xlsx yang valid.',
    ERROR_NO_WORKSHEET: 'Worksheet tidak ditemukan.',
    ERROR_EMPTY_WORKBOOK: 'Workbook kosong — tidak ada data.',
    ERROR_EMPTY_WORKSHEET: 'Worksheet tidak memiliki data.',
    ERROR_MIN_COLUMNS: 'Jumlah kolom kurang dari minimum yang diizinkan.',
    ERROR_NO_DATA: 'Tidak ada data setelah baris header.',
    ERROR_HEADER_COUNT: 'Jumlah header tidak sesuai template.',
    ERROR_HEADER_NAME: 'Nama header tidak sesuai template.',
    ERROR_HEADER_ORDER: 'Urutan header tidak sesuai template.',
    ERROR_REQUIRED_VALUE: 'Kolom wajib diisi.',
    ERROR_TYPE_MISMATCH: 'Tipe data tidak sesuai.',
    ERROR_VALUE_RANGE: 'Nilai berada di luar rentang yang diizinkan.',
    ERROR_UNKNOWN: 'Terjadi kesalahan tak terduga.',
    VALIDATION_VALID: 'Struktur workbook valid.',
    VALIDATION_INVALID: 'Struktur workbook tidak valid.',
    VALIDATION_WARNINGS: 'Peringatan',
    VALIDATION_EMPTY: 'Tidak ada error atau peringatan.',
    VALIDATION_ROW: 'Baris',
    VALIDATION_COLUMN: 'Kolom',
    VALIDATION_WHOLE_WORKBOOK: 'Seluruh workbook',
    VALIDATION_EXPECTED: 'Diharapkan',
    VALIDATION_FOUND: 'Ditemukan',
    VALIDATION_NORMALIZED_HEADERS: 'Header ternormalisasi',
    VALIDATION_ROW_TITLE: 'Validasi Baris Data',
    VALIDATION_ROW_OK: 'Semua baris data valid.',
    VALIDATION_ROW_SUMMARY: (invalid: number, total: number) =>
      `${invalid} dari ${total} baris bermasalah.`,
    VALIDATION_ROW_MORE: (count: number) => `...dan ${count} baris lainnya.`,
    PREVIEW_TITLE: 'Pratinjau Import Buku',
    PREVIEW_FILE: 'File:',
    PREVIEW_SHEET_NAME: 'Nama Worksheet',
    PREVIEW_ROW_COUNT: 'Jumlah Baris',
    PREVIEW_COLUMN_COUNT: 'Jumlah Kolom',
    PREVIEW_TABLE: 'Pratinjau Data Mentah',
    PREVIEW_LOADING: 'Memproses file Excel...',
    PREVIEW_EMPTY: 'Tidak ada file yang dipilih. Mulai dari halaman Import Buku.',
    PREVIEW_ROW_NUMBER: 'No',
    PREVIEW_SHOWING_ROWS: (shown: number, total: number) =>
      `Menampilkan ${shown} dari ${total} baris.`,
    IMPORT_ACTION: 'Import Buku',
    IMPORT_PROCESSING: 'Memproses import...',
    IMPORT_SUCCESS: 'Import selesai.',
    IMPORT_ERROR: 'Terjadi kesalahan saat mengimpor buku. Silakan coba lagi.',
    COMMIT_HINT: 'Verifikasi pratinjau di atas, lalu klik "Import Buku" untuk menyimpan data ke database.',
    BACK_TO_BOOKS: 'Kembali ke Daftar Buku',
    RESULT_TITLE: 'Import selesai',
    RESULT_ALL_OK: 'Semua data berhasil diimport.',
    RESULT_BOOKS_CREATED: 'Buku berhasil dibuat',
    RESULT_COPIES_CREATED: 'Book Copy berhasil dibuat',
    RESULT_FAILED_ROWS: 'Baris gagal',
    RESULT_AMBIGUOUS: 'Judul buku tidak unik (ambigu).',
    RESULT_TITLE_MISSING: 'Judul tidak boleh kosong.',
    RESULT_ENTITY_MISSING: 'Entitas (Penulis/Penerbit/Kategori) tidak ditemukan.',
    RESULT_ISBN_DUPLICATE: 'ISBN sudah digunakan.',
    RESULT_CREATE_FAILED: 'Gagal menyimpan buku.',
    RESULT_COPY_CREATE_FAILED: 'Jumlah Copy harus lebih dari 0.',
  },
  MEMBER_IMPORT: {
    TITLE: 'Import Anggota',
    SUBTITLE: 'Import data anggota (siswa) dari file Excel (.xlsx).',
    UPLOAD_STEP_TITLE: 'Unggah File Excel',
    UPLOAD_STEP_DESC: 'Download template, isi data anggota sesuai kolom yang tersedia, lalu unggah file Excel di sini.',
    SCOPE_TITLE: 'Penempatan Kelas',
    SCOPE_DESC: 'Tentukan Tahun Ajaran dan Kurikulum untuk penempatan kelas anggota yang diimport.',
    YEAR: 'Tahun Ajaran',
    CURRICULUM: 'Kurikulum',
    SELECT_YEAR: 'Pilih Tahun Ajaran',
    SELECT_CURRICULUM: 'Pilih Kurikulum',
    SCOPE_LOADING: 'Memuat data tahun ajaran & kurikulum...',
    SCOPE_LOAD_ERROR: 'Gagal memuat data tahun ajaran/kurikulum. Tutup dialog lalu coba lagi.',
    REQUIRE_SCOPE: 'Pilih Tahun Ajaran dan Kurikulum terlebih dahulu untuk memeriksa data.',
    PICK_FILE: 'Pilih File',
    DOWNLOAD_TEMPLATE: 'Download Template',
    DOWNLOAD_PROCESSING: 'Menyiapkan template...',
    DOWNLOAD_SUCCESS: 'Template Import Anggota v1 berhasil diunduh.',
    DOWNLOAD_CANCELLED: 'Unduhan template dibatalkan.',
    DOWNLOAD_ERROR: 'Gagal mengunduh template.',
    PARSING: 'Memproses file Excel...',
    PARSE_ERROR: 'File gagal dibaca. Pastikan file merupakan .xlsx yang valid.',
    PREVIEW_CHECKING: 'Memeriksa data ke database...',
    PREVIEW_SYSTEM_ERROR: 'Gagal memeriksa data ke database. Pastikan aplikasi berjalan normal, lalu unggah ulang file.',
    CLOSE: 'Tutup',
    MESSAGES: {
      requiredValue: (label: string) => `${label} wajib diisi.`,
      invalidGender: (label: string) => `${label} tidak valid.`,
      invalidDate: (label: string) => `${label} tidak valid.`,
      duplicateNisnInDb: (label: string) => `${label} sudah terdaftar di database.`,
      duplicateEmailInDb: (label: string) => `${label} sudah terdaftar di database.`,
      classNotFound: (label: string) => `Kelas ${label} tidak ditemukan.`,
      classAmbiguous: (label: string) => `Kelas ${label} ambigu.`,
      importFailed: () => 'Import sedang berjalan. Tunggu hingga selesai.',
      createFailed: () => 'Gagal menyimpan data anggota. Silakan coba lagi.',
    },
    PREVIEW_TITLE: 'Pratinjau Data',
    SUMMARY_TOTAL: 'Total',
    SUMMARY_VALID: 'Valid',
    SUMMARY_ERROR: 'Error',
    SUMMARY_DUPLICATE: 'Duplicate',
    HEADER_BARIS: 'Baris',
    HEADER_NAMA: 'Nama',
    HEADER_KELAS: 'Kelas',
    HEADER_NISN: 'NISN',
    HEADER_STATUS: 'Status',
    HEADER_KETERANGAN: 'Keterangan',
    NOTE_VALID: '-',
    NOTE_DUPLICATE_NISN: (baris: string) => `NISN duplikat dengan baris ${baris}.`,
    NOTE_DUPLICATE_EMAIL: (baris: string) => `Email duplikat dengan baris ${baris}.`,
    STATUS_VALID: 'Valid',
    STATUS_ERROR: 'Error',
    STATUS_DUPLICATE: 'Duplicate',
    PREVIEW_MORE_ROWS: (count: number) => `... dan ${count} data lainnya.`,
    IMPORT_BUTTON: 'Import',
    IMPORTING: 'Memproses import...',
    IMPORT_SUCCESS: 'Import Berhasil',
    IMPORT_SUCCESS_DESC: 'Data anggota berhasil diimport.',
    IMPORT_FAILED: 'Import Gagal',
    IMPORT_SYSTEM_ERROR: 'Terjadi kesalahan sistem saat import. Silakan coba lagi.',
    RESULT_TOTAL: 'Total Baris',
    RESULT_CREATED: 'Berhasil',
    RESULT_SKIPPED: 'Dilewati',
    RESULT_FAILED: 'Gagal',
    RESULT_WARNINGS: 'Peringatan',
    PROGRESS_TITLE: 'Status Import',
    PROGRESS_STAGES: {
      preparing: 'Preparing',
      'checking-duplicate': 'Checking Duplicate',
      'resolving-class': 'Resolving Class',
      'generating-number': 'Generating Member Number',
      saving: 'Saving Database',
      completed: 'Completed',
    },
  },
  ACTION: {
    VIEW: 'Lihat',
    EDIT: 'Edit',
    DELETE: 'Hapus',
  },
  ENROLLMENT_HISTORY: {
    TITLE: 'Riwayat Enrollment',
    NEW: 'Riwayat Enrollment',
    SUBTITLE: 'Riwayat pendaftaran kelas anggota.',
    EMPTY: 'Belum ada riwayat enrollment.',
    EMPTY_DESC: 'Anggota belum pernah di-enroll ke kelas mana pun.',
    HEADER_ACADEMIC_YEAR: 'Tahun Ajaran',
    HEADER_CURRICULUM: 'Kurikulum',
    HEADER_CLASS: 'Kelas',
    HEADER_STATUS: 'Status',
    HEADER_JOINED_AT: 'Bergabung',
    HEADER_LEFT_AT: 'Keluar',
    HEADER_NOTE: 'Catatan',
    DETAIL: 'Detail',
    DETAIL_CREATED_AT: 'Dibuat',
    DETAIL_UPDATED_AT: 'Diperbarui',
    ACTIVE: 'Aktif',
    PROMOTED: 'Naik Kelas',
    REPEATED: 'Tinggal Kelas',
    REDISTRIBUTED: 'Alih Kelas',
    TRANSFERRED: 'Pindah Sekolah',
    DROPPED: 'Keluar',
    GRADUATED: 'Lulus',
  },
  LABEL_PREVIEW: {
    TITLE: 'Pratinjau Label',
    PRINT: 'Cetak',
    PRINTING: 'Mencetak...',
    LOADING: 'Memuat pratinjau...',
    NO_DATA: 'Tidak ada label untuk ditampilkan.',
    BOOK_NOT_FOUND: 'Buku tidak ditemukan.',
    ERROR: 'Terjadi kesalahan saat memuat pratinjau label.',
  },
  FILE_MENU: {
    LABEL: 'File',
    BACKUP: 'Backup',
    RESTORE: 'Restore',
    CETAK_KARTU_PEMINJAMAN: 'Cetak Kartu Peminjaman',
    EXIT: 'Exit',
  },
  RECEIPT_PREVIEW: {
    TITLE: 'Pratinjau Kartu Peminjaman',
    LOADING: 'Memuat pratinjau kartu...',
    NO_DATA: 'Tidak ada kartu untuk ditampilkan.',
    BORROW_NOT_FOUND: 'Data peminjaman tidak ditemukan.',
    ERROR: 'Terjadi kesalahan saat memuat pratinjau kartu.',
    ZOOM_OUT: 'Zoom -',
    ZOOM_IN: 'Zoom +',
    ZOOM_RESET: '100%',
    FIT_WIDTH: 'Fit Width',
    PRINT: 'Cetak',
    PRINTING: 'Mencetak...',
    PRINT_SILENT: 'Cetak tanpa dialog (silent)',
    SAVE_PDF: 'Simpan PDF',
    SAVING_PDF: 'Menyimpan PDF...',
    CLOSE: 'Tutup',
    PAGE: 'Halaman',
    PREV_PAGE: 'Halaman sebelumnya',
    NEXT_PAGE: 'Halaman berikutnya',
    PDF_SAVED: 'PDF tersimpan: ',
    PRINT_ERROR: 'Gagal mencetak.',
    PDF_ERROR: 'Gagal menyimpan PDF.',
  },
  BORROW_CARD_PRINT: {
    TITLE: 'Cetak Kartu Peminjaman',
    SUBTITLE: 'Pilih transaksi peminjaman yang masih aktif untuk melihat pratinjau kartunya.',
    LOADING: 'Memuat daftar peminjaman aktif...',
    ERROR: 'Terjadi kesalahan saat memuat daftar peminjaman.',
    EMPTY: 'Tidak ada peminjaman aktif.',
    EMPTY_DESC: 'Transaksi peminjaman yang masih berjalan akan muncul di sini.',
    COL_BORROW_DATE: 'Tanggal',
    COL_NUMBER: 'No. Transaksi',
    COL_MEMBER: 'Nama Anggota',
    COL_MEMBER_NUMBER: 'Nomor Anggota',
    COL_ITEMS: 'Jumlah Buku',
    COL_DUE_DATE: 'Jatuh Tempo',
    COL_ACTION: 'Aksi',
    ACTION_PREVIEW: 'Lihat Preview',
  },
  PROMOTION: {
    TITLE: 'Riwayat Promosi',
    SUBTITLE: 'Riwayat run kenaikan kelas antar tahun ajaran.',
    EMPTY: 'Belum ada run promosi.',
    EMPTY_DESC: 'Run promosi akan muncul di sini setelah dieksekusi.',
    LOADING: 'Memuat riwayat promosi...',
    ERROR: 'Terjadi kesalahan saat memuat riwayat promosi.',
    HEADER_RUN: 'Run',
    HEADER_ACADEMIC_YEAR: 'Tahun Ajaran',
    HEADER_DATE: 'Tanggal',
    HEADER_TOTAL: 'Total Member',
    HEADER_PROMOTED: 'Naik Kelas',
    HEADER_GRADUATED: 'Lulus',
    HEADER_REPEATED: 'Tinggal Kelas',
    HEADER_REDISTRIBUTED: 'Alih Kelas',
    HEADER_TRANSFERRED: 'Pindah',
    HEADER_DROPPED: 'Keluar',
    HEADER_NO_TARGET: 'Tanpa Target',
    HEADER_ERROR: 'Error',
    HEADER_STATUS: 'Status',
    DETAIL: 'Detail',
    DETAIL_TITLE: 'Detail Run Promosi',
    DETAIL_SUBTITLE: 'Hasil eksekusi run kenaikan kelas.',
    DETAIL_ITEMS: 'Item',
    DETAIL_ITEM_EMPTY: 'Run ini tidak memiliki item.',
    BACK_TO_LIST: 'Kembali ke Riwayat Promosi',
    ITEM_HEADER_MEMBER: 'Member',
    ITEM_HEADER_SOURCE_CLASS: 'Kelas Asal',
    ITEM_HEADER_TARGET_CLASS: 'Kelas Tujuan',
    ITEM_HEADER_OUTCOME: 'Hasil',
    ITEM_HEADER_MESSAGE: 'Catatan',
    STATUS_SUCCESS: 'Sukses',
    STATUS_PARTIAL: 'Sebagian',
    STATUS_FAILED: 'Gagal',
    OUTCOME_PROMOTED: 'Naik Kelas',
    OUTCOME_GRADUATED: 'Lulus',
    OUTCOME_REPEATED: 'Tinggal Kelas',
    OUTCOME_REDISTRIBUTED: 'Alih Kelas',
    OUTCOME_NO_TARGET: 'Tanpa Target',
    OUTCOME_ERROR: 'Error',
    MODE_AUTOMATIC: 'Otomatis',
    MODE_MAPPING: 'Pemetaan',
    MODE_BULK_EDIT: 'Edit Massal',
  },
  PROMOTION_OPERATOR: {
    TITLE: 'Promosi',
    SUBTITLE: 'Jalankan kenaikan kelas antar tahun ajaran.',
    SOURCE_YEAR: 'Tahun Ajaran Sumber',
    TARGET_YEAR: 'Tahun Ajaran Tujuan',
    SOURCE_CLASS: 'Kelas Sumber',
    ALL_CLASSES: 'Semua Kelas (seluruh kelas tahun sumber)',
    PREVIEW: 'Preview',
    PREVIEWING: 'Memuat preview...',
    EXECUTE: 'Eksekusi Promosi',
    EXECUTING: 'Mengeksekusi...',
    RESULT_TITLE: 'Hasil Preview',
    RESULT_HINT: 'Eksekusi menghasilkan hasil yang sama dengan preview (engine keputusan tunggal).',
    EMPTY_TITLE: 'Preview belum dijalankan',
    EMPTY_DESC: 'Pilih tahun ajaran sumber & tujuan lalu tekan Preview.',
    CONFIRM_EXECUTE: 'Lanjutkan eksekusi promosi? Hasil akan sama dengan preview.',
    TOTAL: 'Total Member',
    MEMBER_COLUMN: 'Member',
    CLASS_COLUMN: 'Kelas Asal',
    TARGET_COLUMN: 'Kelas Tujuan',
    OUTCOME_COLUMN: 'Hasil',
    MESSAGE_COLUMN: 'Catatan',
  },
  REPORT: {
    TITLE: 'Laporan',
    SUBTITLE: 'Pilih jenis laporan untuk melihat ringkasan data perpustakaan.',
    BORROWINGS: 'Laporan Peminjaman',
    BORROWINGS_DESC: 'Rekap seluruh transaksi peminjaman buku pada periode tertentu.',
    OPEN: 'Buka',
    FROM: 'Dari Tanggal',
    TO: 'Sampai Tanggal',
    STATUS: 'Status',
    STATUS_ALL: 'Semua Status',
    SEARCH_LABEL: 'Pencarian',
    SEARCH: 'Cari nomor transaksi, nomor/nama anggota, atau judul buku...',
    TOTAL_TRANSACTIONS: 'Total Transaksi',
    ACTIVE: 'Sedang Dipinjam',
    COMPLETED: 'Sudah Kembali',
    OVERDUE: 'Terlambat',
    COL_DATE: 'Tanggal',
    COL_NUMBER: 'Nomor Transaksi',
    COL_MEMBER: 'Nama Anggota',
    COL_CLASS: 'Kelas',
    COL_TITLE: 'Judul Buku',
    COL_DUE: 'Jatuh Tempo',
    COL_STATUS: 'Status',
    STATUS_ACTIVE: 'Dipinjam',
    STATUS_COMPLETED: 'Dikembalikan',
    STATUS_OVERDUE: 'Terlambat',
    RETURNS: 'Laporan Pengembalian',
    RETURNS_DESC: 'Rekap seluruh pengembalian buku pada periode tertentu.',
    TOTAL_RETURNS: 'Total Pengembalian',
    ON_TIME: 'Tepat Waktu',
    LATE: 'Terlambat',
    COL_RETURN_DATE: 'Tanggal Kembali',
    COL_DURATION: 'Lama Pinjam',
    DAYS: 'hari',
    OVERDUES: 'Laporan Keterlambatan',
    OVERDUES_DESC: 'Rekap seluruh peminjaman yang melewati jatuh tempo.',
    TOTAL_OVERDUE: 'Total Terlambat',
    STILL_LATE: 'Belum Dikembalikan',
    RETURNED_LATE: 'Sudah Dikembalikan Terlambat',
    COL_BORROW_DATE: 'Tanggal Pinjam',
    COL_LATE_DAYS: 'Hari Terlambat',
    STATUS_STILL_LATE: 'Masih Terlambat',
    STATUS_RETURNED_LATE: 'Sudah Dikembalikan Terlambat',
    MEMBERS: 'Laporan Anggota',
    MEMBERS_DESC: 'Rekap seluruh anggota perpustakaan beserta status keanggotaan.',
    TOTAL_MEMBERS: 'Total Anggota',
    MEMBERSHIP_STATUS: 'Status Keanggotaan',
    MEMBERSHIP_ALL: 'Semua Status',
    MEMBERSHIP_ACTIVE: 'Aktif',
    MEMBERSHIP_INACTIVE: 'Nonaktif',
    CLASS_FILTER: 'Kelas',
    CLASS_ALL: 'Semua Kelas',
    SEARCH_MEMBER: 'Cari nomor anggota atau nama...',
    COL_MEMBER_NUMBER: 'Nomor Anggota',
    COL_NAME: 'Nama',
    COL_JOINED: 'Tanggal Bergabung',
    COLLECTIONS: 'Laporan Koleksi Buku',
    COLLECTIONS_DESC: 'Rekap seluruh koleksi buku beserta jumlah dan kondisi eksemplar.',
    TOTAL_TITLES: 'Total Judul',
    TOTAL_COPIES: 'Total Eksemplar',
    TOTAL_ASSET_VALUE: 'Nilai Aset',
    COL_ISBN: 'ISBN',
    COL_AUTHOR: 'Penulis',
    COL_PUBLISHER: 'Penerbit',
    COL_CATEGORY: 'Kategori',
    COL_PUBLICATION_YEAR: 'Tahun Terbit',
    COL_COPY_COUNT: 'Jumlah Eksemplar',
    STATUS_AVAILABLE: 'Tersedia',
    STATUS_BORROWED: 'Dipinjam',
    STATUS_LOST: 'Hilang',
    CONDITION_DAMAGED: 'Rusak',
    CATEGORY_FILTER: 'Kategori',
    CATEGORY_ALL: 'Semua Kategori',
    SEARCH_BOOK: 'Cari judul, ISBN, penulis, atau penerbit...',
  },
  BACKUP_RESTORE: {
    BACKUP_TITLE: 'Backup Data',
    BACKUP_SUBTITLE: 'Buat salinan cadangan seluruh data perpustakaan.',
    STORAGE_LOCATION: 'Lokasi Penyimpanan',
    STORAGE_LOCATION_DESC: 'Backup disimpan otomatis di folder data aplikasi. Lokasi tidak dapat diubah.',
    FIXED_DIR: 'Folder tersimpan',
    SAMPLE_FILENAME: 'Contoh nama file',
    OPEN_FOLDER: 'Buka Folder',
    START_BACKUP: 'Mulai Backup',
    BACKUP_RUNNING: 'Membuat backup...',
    PROGRESS: 'Proses Backup',
    STAGE_VALIDATE: 'Validasi',
    STAGE_COLLECT: 'Collect Data',
    STAGE_MANIFEST: 'Manifest',
    STAGE_COMPRESS: 'Compress',
    STAGE_VERIFY: 'Verify',
    STAGE_FINALIZE: 'Finalize',
    STAGE_COMPLETE: 'Complete',
    BACKUP_SUCCESS: 'Backup berhasil dibuat.',
    BACKUP_WARNING: 'Backup selesai dengan peringatan.',
    BACKUP_FAILED: 'Backup gagal.',
    BACKUP_CANCELLED: 'Backup dibatalkan.',
    RESULT_FILE: 'Nama File',
    RESULT_SIZE: 'Ukuran',
    RESULT_DURATION: 'Durasi',
    RESULT_DIR: 'Lokasi',
    SIZE_MB: 'MB',
    SIZE_KB: 'KB',
    SIZE_BYTES: 'B',
    DURATION_SECONDS: 'detik',
    RESTORE_TITLE: 'Pulihkan Data',
    RESTORE_SUBTITLE: 'Pulihkan data perpustakaan dari file backup.',
    PICK_BACKUP: 'Pilih File Backup',
    PICK_BACKUP_DESC: 'Pilih file backup (.apbackup) untuk melihat isinya.',
    SELECTED_FILE: 'File Terpilih',
    FILE_INFO: 'Informasi Backup',
    FILE_NAME: 'Nama File',
    FILE_SIZE: 'Ukuran',
    BACKUP_DATE: 'Tanggal Backup',
    APP_VERSION: 'Versi Aplikasi',
    SCHEMA_VERSION: 'Schema Version',
    BACKUP_VERSION: 'Backup Version',
    BOOK_COUNT: 'Jumlah Buku',
    MEMBER_COUNT: 'Jumlah Anggota',
    COPY_COUNT: 'Jumlah Eksemplar',
    RESTORE_BUTTON: 'Mulai Pulihkan',
    RESTORE_RUNNING: 'Memulihkan data...',
    RESTORE_PROGRESS: 'Proses Pulihkan',
    RESTORE_STAGE_VALIDATE: 'Validation',
    RESTORE_STAGE_EXTRACT: 'Extract',
    RESTORE_STAGE_VERIFY: 'Verify',
    RESTORE_STAGE_SNAPSHOT: 'Snapshot',
    RESTORE_STAGE_RESTORE: 'Restore',
    RESTORE_STAGE_VERIFY_AFTER: 'Verify',
    RESTORE_STAGE_CLEANUP: 'Cleanup',
    RESTORE_STAGE_COMPLETE: 'Complete',
    RESTORE_CONFIRM_TITLE: 'Pulihkan Data?',
    RESTORE_CONFIRM_MESSAGE: 'Database saat ini akan diganti dengan isi file backup. Proses tidak dapat dibatalkan.',
    RESTORE_CONFIRM_OK: 'Ya, Pulihkan',
    RESTORE_CANCEL: 'Batal',
    RESTORE_SUCCESS: 'Data berhasil dipulihkan.',
    RESTORE_NEEDS_RESTART: 'Data berhasil dipulihkan. Aplikasi perlu dimulai ulang agar perubahan diterapkan.',
    RESTORE_FAILED: 'Pemulihan gagal.',
    RESTORE_CANCELLED: 'Pemulihan dibatalkan.',
    INVALID_FILE: 'File bukan backup valid.',
    NO_FILE: 'Belum ada file dipilih.',
    LOADING_FILE: 'Membaca file backup...',
    EMPTY_BACKUP: 'Belum ada backup yang dibuat.',
  },
  SETTINGS: {
    TITLE: 'Pengaturan',
    SUBTITLE: 'Kelola identitas perpustakaan dan informasi aplikasi.',
    TAB_IDENTITY: 'Identitas Perpustakaan',
    TAB_DATA: 'Manajemen Data',
    TAB_SECURITY: 'Keamanan',
    TAB_APP_INFO: 'Informasi Aplikasi',
    TAB_ABOUT: 'Tentang',
    IDENTITY_SUBTITLE: 'Identitas yang tampil pada kartu peminjaman dan label buku.',
    FIELD_LIBRARY_NAME: 'Nama Perpustakaan',
    FIELD_SCHOOL_NAME: 'Nama Sekolah',
    FIELD_LOGO: 'Logo Perpustakaan',
    FIELD_LIBRARIAN_NAME: 'Nama Pustakawan',
    FIELD_BARCODE_FORMAT: 'Format Barcode',
    BARCODE_FORMAT_SUBTITLE: 'Simbol kode batang pada label buku.',
    FIELD_INVENTORY_PREFIX: 'Awalan Nomor Inventaris',
    INVENTORY_PREFIX_SUBTITLE: 'Awalan nomor inventaris/barcode buku (contoh: INV, BC).',
    INVENTORY_PREFIX_PREVIEW: 'Contoh kode: ',
    VALIDATION_INVENTORY_PREFIX: 'Awalan nomor inventaris hanya huruf/angka, tanpa spasi, maksimal 10 karakter.',
    LOGO_PICK: 'PILIH LOGO',
    LOGO_COMING_SOON: 'Fitur akan tersedia pada tahap berikutnya.',
    SAVE: 'Simpan Perubahan',
    SAVING: 'Menyimpan...',
    SAVED: 'Pengaturan berhasil disimpan.',
    LOADING: 'Memuat...',
    DATA_SUBTITLE: 'Kelola backup dan database aplikasi.',
    DATA_BACKUP: 'Backup Database',
    DATA_BACKUP_DESC: 'Buat salinan cadangan seluruh data perpustakaan.',
    DATA_BACKUP_OPEN: 'Buka Backup',
    DATA_RESTORE: 'Restore Database',
    DATA_RESTORE_DESC: 'Pulihkan data perpustakaan dari file backup.',
    DATA_RESTORE_OPEN: 'Buka Restore',
    DATA_RESET: 'Reset Database',
    DATA_RESET_DESC: 'Kembalikan database ke kondisi awal.',
    RESET_CONFIRM_TITLE: 'Reset Database',
    RESET_CONFIRM_MESSAGE:
      'Seluruh data buku, anggota, peminjaman, pengembalian, promosi, dan inventaris akan DIHAPUS permanen. Data master (Tahun Ajaran, Kurikulum, Kelas), pengaturan, dan akun admin akan dipertahankan. Tindakan ini tidak dapat dibatalkan. Lanjutkan?',
    RESET_CONFIRM_OK: 'Ya, Reset Sekarang',
    RESET_CONFIRM_CANCEL: 'Batal',
    RESET_RUNNING: 'Mereset database...',
    RESET_SUCCESS: 'Database berhasil direset ke kondisi awal.',
    RESET_ERROR: 'Reset database gagal.',
    COMING_SOON: 'Segera Hadir',
    COMING_SOON_HINT: 'Fitur akan tersedia pada tahap berikutnya.',
    SECURITY_SUBTITLE: 'Keamanan akses aplikasi.',
    SECURITY_LOGIN: 'Login Admin',
    SECURITY_LOGIN_DESC: 'Masuk sebagai administrator aplikasi.',
    SECURITY_PASSWORD: 'Ubah Password',
    SECURITY_PASSWORD_DESC: 'Perbarui kata sandi administrator.',
    APP_INFO_SUBTITLE: 'Informasi teknis aplikasi (hanya baca).',
    INFO_APP_VERSION: 'Versi Aplikasi',
    INFO_DB_VERSION: 'Versi Database',
    INFO_BACKUP_VERSION: 'Versi Backup',
    INFO_DB_LOCATION: 'Lokasi Database',
    INFO_BACKUP_LOCATION: 'Lokasi Folder Backup',
    INFO_DB_SIZE: 'Ukuran Database',
    NOT_AVAILABLE: 'Belum tersedia',
    ABOUT_SUBTITLE: 'Informasi aplikasi perpustakaan.',
    ABOUT_NAME: 'Nama Aplikasi',
    ABOUT_VERSION: 'Versi',
    ABOUT_COPYRIGHT: 'Copyright',
    ABOUT_DEVELOPER: 'Developer',
    VALIDATION_LOADING: 'Data tidak tersedia.',
    VALIDATION_LIBRARY_NAME: 'Nama Perpustakaan wajib diisi.',
    FIELD_PRINTER: 'Printer Kartu Peminjaman',
    PRINTER_SUBTITLE: 'Printer yang dipakai untuk mencetak kartu peminjaman (A6).',
    PRINTER_AUTO: 'Deteksi otomatis (A6 / printer default)',
    PRINTER_NONE: 'Tidak ada printer terdeteksi',
    PRINTER_LOADING: 'Memuat daftar printer...',
    PRINTER_REFRESH: 'Muat Ulang',
  },
  AUTH: {
    APP_NAME: 'APLibrary',
    APP_SUBTITLE: 'Sistem Manajemen Perpustakaan',
    SETUP_TITLE: 'Setup Awal Admin',
    SETUP_SUBTITLE:
      'Buat akun administrator untuk mengelola aplikasi. Hanya dilakukan sekali saat pertama kali aplikasi dijalankan.',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Konfirmasi Password',
    SETUP_BUTTON: 'Buat Admin & Masuk',
    SETUP_PROCESSING: 'Menyimpan...',
    ERR_USERNAME_REQUIRED: 'Username wajib diisi.',
    ERR_PASSWORD_MIN: 'Password minimal 8 karakter.',
    ERR_PASSWORD_MAX: 'Password maksimal 128 karakter.',
    ERR_PASSWORD_MISMATCH: 'Password dan konfirmasi password tidak sama.',
    LOGIN_TITLE: 'Login',
    LOGIN_SUBTITLE: 'Masukkan kata sandi untuk melanjutkan.',
    LOGIN_BUTTON: 'Masuk',
    LOGIN_PROCESSING: 'Memverifikasi...',
    FOOTER_AUTHORIZED: 'Akses hanya untuk pengguna berwenang.',
    ERR_PASSWORD_REQUIRED: 'Password wajib diisi.',
    CURRENT_PASSWORD: 'Password Lama',
    NEW_PASSWORD: 'Password Baru',
    ERR_CURRENT_PASSWORD_REQUIRED: 'Password lama wajib diisi.',
    CHANGE_PASSWORD_TITLE: 'Ubah Password',
    CHANGE_PASSWORD_SUBTITLE: 'Perbarui kata sandi administrator. Anda akan tetap login.',
    CHANGE_PASSWORD_BUTTON: 'Simpan Perubahan',
    CHANGE_PASSWORD_PROCESSING: 'Menyimpan...',
    CHANGE_PASSWORD_SUCCESS: 'Password berhasil diubah. Session tetap aktif.',
    CHANGE_PASSWORD_BACK: 'Kembali ke Pengaturan',
    LOGOUT: 'Logout',
    LOGOUT_FAILED: 'Gagal logout.',
    LOADING: 'Memuat...',
    LOAD_ERROR: 'Gagal memuat status autentikasi.',
    RETRY: 'Coba Lagi',
    SUBMIT_ERROR_DEFAULT: 'Terjadi kesalahan. Coba lagi.',
  },
} as const
